// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PwaProject2.Server.Data;

namespace PwaProject2.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220107074905_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PwaProject2.Shared.Product", b =>
                {
                    b.Property<int?>("inId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("dcPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("flgOutOfStock")
                        .HasColumnType("bit");

                    b.Property<int?>("inQuantity")
                        .HasColumnType("int");

                    b.Property<string>("stDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("inId");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
